logging:
  level: INFO
  loggers:
    org.cheise_proj: DEBUG

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: postgres
  url: jdbc:postgresql://localhost:5432/users
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false


swagger:
  resourcePackage: org.cheise_proj
  title: User API
  version: v1
  description: User service API
  license: Apache 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0

migrationFileLocation: migrations.xml
