version: '3'

services:
  db:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users

  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-5
    container_name: graphite
    ports:
      - "80:80"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"
  #    volumes:
  #      - $PWD/graphite_data:/opt/graphite/storage

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
    volumes:
      #      - $PWD/grafana_data:/var/lib/grafana
      - $PWD/grafana_data/dashboards:/var/lib/grafana/dashboards
      - $PWD/grafana_data/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - $PWD/grafana_data/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    depends_on:
      - graphite

  prometheus-exporter:
    image: prom/pushgateway:v1.5.0
    ports:
      - "9091:9091"

  prometheus:
    image: prom/prometheus:v2.37.9
    command: "--config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle"
    ports:
      - "9090:9090"
    volumes:
      - $PWD/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  user-service:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      GRAPHITE_ENDPOINT: graphite
      GRAPHITE_PORT: 2003
      GRAPHITE_REPORT_INTERVAL: 10
      DATABASE_HOST: jdbc:postgresql://db/users
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      - db
      - graphite
      - prometheus-exporter
