apiVersion: 1
datasources:
  - name: Graphite
    type: graphite
    access: proxy
    url: http://graphite:80
    isDefault: true
    editable: false

  - name: k6influxdb
    type: influxdb
    access: proxy
    database: k6
    url: http://influxdb:8086
